#ifndef ENEMYIMAGE_H_INCLUDED
#define ENEMYIMAGE_H_INCLUDED

bool bossMoveLeft = false, bossMoveRight = false;
void bossEnemyPositionChange();

int bossEnemyAliveTimeSeconds = 120; // 2 minutes (120 seconds)
bool bossEnemyAliveTime = true;
//BOSS ENEMY

//int additionalHealthBarX = 615;
int additionalHealthBarX = 1280;
int additionalHealthBarY = 360;
int additionalHealthBarIndex = 0;
int additionalHealth = 146;
bool healthMechanism = false;


int normalHealthBarX = 1280;
int normalHealthBarY = 585;
//int normalHealthBarX = 865;


int timeBarX = 421;
int timeBarY = 720;
//int timeBarY = 660;

int dracoVenatorEffectIndex = 0;



char bossEnemyStance[30][50] = {
	"image//Enemy//Boss Enemy//Stance//Idle_0001.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0002.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0003.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0004.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0005.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0006.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0007.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0008.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0009.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0010.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0011.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0012.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0013.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0014.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0015.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0016.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0017.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0018.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0019.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0020.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0021.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0022.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0023.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0024.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0025.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0026.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0027.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0028.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0029.bmp",
	"image//Enemy//Boss Enemy//Stance//Idle_0030.bmp"
};

char bossEnemyAppear[24][50] = {
	"image//Enemy//Boss Enemy//Appear//Appear_0001.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0002.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0003.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0004.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0005.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0006.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0007.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0008.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0009.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0010.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0011.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0012.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0013.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0014.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0015.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0016.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0017.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0018.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0019.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0020.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0021.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0022.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0023.bmp",
	"image//Enemy//Boss Enemy//Appear//Appear_0024.bmp"
};


char bossEnemyBackwardWalk[20][70] = {								// left dike jaitiche
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0001.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0002.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0003.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0004.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0005.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0006.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0007.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0008.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0009.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0010.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0011.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0012.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0013.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0014.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0015.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0016.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0017.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0018.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0019.bmp",
	"image//Enemy//Boss Enemy//Walk//Backward Walk//Walk_0020.bmp",
};

char bossEnemyForwardWalk[20][70] = {
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0001.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0002.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0003.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0004.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0005.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0006.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0007.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0008.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0009.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0010.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0011.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0012.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0013.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0014.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0015.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0016.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0017.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0018.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0019.bmp",
	"image//Enemy//Boss Enemy//Walk//Forward Walk//Walk_0020.bmp",
};




char bossEnemyForwardAttack_1[24][90] = {
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0001.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0002.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0003.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0004.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0005.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0006.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0007.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0008.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0009.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0010.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0011.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0012.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0013.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0014.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0015.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0016.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0017.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0018.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0019.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0020.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0021.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0022.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0023.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Forward Attack//Attack_01_0024.bmp",
};




char bossEnemyBackwardAttack_1[24][90] = {
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0001.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0002.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0003.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0004.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0005.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0006.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0007.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0008.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0009.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0010.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0011.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0012.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0013.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0014.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0015.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0016.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0017.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0018.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0019.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0020.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0021.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0022.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0023.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_01//Backward Attack//Attack_01_0024.bmp",
};

char bossEnemyForwardAttack_3[30][90] = {
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0001.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0002.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0003.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0004.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0005.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0006.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0007.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0008.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0009.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0010.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0011.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0012.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0013.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0014.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0015.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0016.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0017.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0018.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0019.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0020.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0021.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0022.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0023.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0024.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0025.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0026.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0027.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0028.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0029.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Forward Attack//Fire_0030.bmp"
};


char bossEnemyBackwardAttack_3[30][90] = {
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0001.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0002.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0003.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0004.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0005.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0006.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0007.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0008.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0009.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0010.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0011.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0012.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0013.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0014.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0015.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0016.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0017.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0018.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0019.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0020.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0021.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0022.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0023.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0024.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0025.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0026.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0027.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0028.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0029.bmp",
	"image//Enemy//Boss Enemy//Attack//Attack_03_(fire)//Backward Attack//Fire_0030.bmp"
};


char additionalHealthBar[146][60] = {
	"image\\Health\\HeroAditional\\frame_001_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_002_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_003_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_004_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_005_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_006_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_007_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_008_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_009_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_010_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_011_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_012_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_013_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_014_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_015_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_016_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_017_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_018_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_019_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_020_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_021_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_022_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_023_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_024_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_025_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_026_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_027_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_028_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_029_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_030_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_031_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_032_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_033_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_034_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_035_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_036_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_037_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_038_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_039_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_040_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_041_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_042_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_043_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_044_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_045_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_046_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_047_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_048_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_049_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_050_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_051_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_052_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_053_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_054_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_055_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_056_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_057_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_058_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_059_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_060_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_061_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_062_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_063_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_064_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_065_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_066_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_067_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_068_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_069_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_070_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_071_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_072_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_073_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_074_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_075_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_076_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_077_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_078_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_079_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_080_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_081_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_082_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_083_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_084_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_085_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_086_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_087_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_088_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_089_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_090_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_091_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_092_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_093_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_094_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_095_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_096_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_097_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_098_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_099_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_100_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_101_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_102_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_103_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_104_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_105_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_106_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_107_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_108_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_109_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_110_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_111_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_112_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_113_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_114_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_115_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_116_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_117_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_118_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_119_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_120_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_121_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_122_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_123_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_124_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_125_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_126_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_127_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_128_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_129_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_130_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_131_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_132_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_133_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_134_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_135_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_136_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_137_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_138_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_139_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_140_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_141_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_142_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_143_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_144_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_145_delay-0.04s.bmp",
	"image\\Health\\HeroAditional\\frame_145_delay-0.04s.bmp"
};


char dracoVenatorEffect[60][70] = {
	"image//Effect//Draco Venator Effect//frame_00_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_01_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_02_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_03_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_04_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_05_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_06_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_07_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_08_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_09_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_10_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_11_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_12_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_13_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_14_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_15_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_16_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_17_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_18_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_19_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_20_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_21_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_22_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_23_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_24_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_25_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_26_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_27_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_28_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_29_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_30_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_31_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_32_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_33_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_34_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_35_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_36_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_37_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_38_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_39_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_40_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_41_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_42_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_43_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_44_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_45_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_46_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_47_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_48_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_49_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_50_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_51_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_52_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_53_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_54_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_55_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_56_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_57_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_58_delay-0.1s.bmp",
	"image//Effect//Draco Venator Effect//frame_59_delay-0.1s.bmp"
};

#endif